lab3/lab3/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('qq.urls')),
    url(r'^post/', include('post.urls', namespace="post")),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^accounts/', include('registration.backends.simple.urls')),
] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lab3/post/urls.py
from django.conf.urls import url
from .import views

urlpatterns = [
   # url(r'^$', views.index, name='index'),
    url(r'^create/', views.createPost, name='create'),
    url(r'^remove/(?P<post_id>\d+)/$', views.removePost, name='remove'),
    url(r'^edit/(?P<post_id>\d+)/', views.editPost, name='edit'),
]

lab3/qq/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views
urlpatterns = [
    url(r'^Den/', views.Den, name='Den'),
    url(r'^sales/', views.sales, name='sales'),
    url(r'^news/', views.news, name='news'),
]

lab3/users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^edit/$', views.editUser, name='edit'),
    url(r'^blog/(?P<user_id>\d+)/$', views.userBlog, name='blog'),
]

lab3/users/models.py
from django.conf import settings
from django.db import models
from .storage import OverwriteStorage



def profile_pic_path(instance, filename):
    return '/'.join(['content', 'user_' + str(instance.id), 'profile_pic.jpg'])

class UserInfo(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL)
    name = models.CharField(max_length=30, default='first name')
    surname = models.CharField(max_length=30, default='second name')
    phone = models.CharField(max_length=20, blank=True)
    about = models.CharField(max_length=255, blank=True)
    profile_image = models.ImageField(blank=True,  storage=OverwriteStorage(), upload_to=profile_pic_path)

    def __str__(self):
        return self.name + ' ' + self.user.email

lab3/users/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect, get_list_or_404, render_to_response
from django.template import RequestContext
from .forms import UserForm
from .models import Post
from .models import UserInfo
from .models import profile_pic_path


def index(request):
    user_list = UserInfo.objects.all()
    return render(request, 'SIB.html/', {'user_list': user_list})

def userBlog(request, user_id):
    post_list = get_list_or_404(Post.objects.order_by('-date_published'), author=user_id)
    #post_list = Post.objects.order_by('-date_published').filter(author=user_id)
    paginator = Paginator(post_list, 2)

    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        posts = paginator.page(paginator.num_pages)

    return render(request, 'users/blog.html', {'post_list': posts})

def editUser(request):
    if not request.user.is_authenticated():
        return redirect('users:index')

    user_model = get_object_or_404(UserInfo, pk=request.user.userinfo.id)

    if request.method == 'POST':
        user_form = UserForm(request.POST, request.FILES)

        if user_form.is_valid():
            user_model.name = user_form.cleaned_data['name']
            user_model.surname = user_form.cleaned_data['surname']
            request.user.email = user_form.cleaned_data['email']
            request.user.save()
            user_model.phone = user_form.cleaned_data['phone']
            user_model.about = user_form.cleaned_data['about']
            if user_form.cleaned_data['profile_image'] is not None:
                user_model.profile_image = user_form.cleaned_data['profile_image']
            profile_pic_path(request.user, 'something')
            user_model.save()

            return HttpResponseRedirect(reverse('users:blog', args=(request.user.id,)))

    else:
        user_form = UserForm(instance=user_model)
        user_form.initial['email'] = request.user.email

    return render_to_response('users/editUser.html', {'user_form': user_form}, context_instance=RequestContext(request))

lab3/users/templates/users/blog.html
{% extends 'boby.html' %}

{% block content %}
    <div class="row">




        <div class="col-sm-2 " style="word-wrap: break-word">
            <p align = "center">
               {% if user.is_authenticated %}
                <a href="{% url 'users:edit' %}" style="font-size: small">Редактировать профиль</a>
                {% if user.userinfo.profile_image.url|length > 0 %}
                    {% if user.userinfo.profile_image.url != '/media/False'  %}
                        <img src="{{ user.userinfo.profile_image.url }}" class="img-responsive">
                    {% else %}
                        <br>
                    {% endif %}
                {% else %}
                    <br>
                {% endif %}
                {{ user.userinfo.name }}
                <br>
                {{ user.userinfo.surname }}
                <br>
                {{ user.email }}
                <br>
                {{ user.userinfo.phone }}
                <br>
                {{ user.userinfo.about }}
            {% endif %}
               </p>

        </div>


        <div class="col-sm-8" style="word-wrap: break-word">
            {% if user.is_authenticated %}
            <p><button class="col-sm-2"> <a href="{% url 'post:create' %}">Создать запись</a></button></p>
            {% endif %}
            <h3 class="text-info text-center" >Блог</h3>

            {% for post in post_list %}
                <div class="box">
                    <div class="row">
                        <div class="col-sm-12">
                            <h4 class="text-info text-center">{{ post.title }}</h4>
                        </div>
                            <div class="col-sm-12">
                                <p>{{ post.content }}</p>
                            </div>
                        <span class="col-sm-3">{{ post.date_published }}</span>
                        {% if user.is_authenticated %}

                            <p><button class="col-sm-2 col-sm-offset-4"> <a href="{% url 'post:edit' post.id %}">Редактировать</a></button></p>
                            <p><button class="col-sm-2"> <a href="{% url 'post:remove' post.id %}">Удалить</a></button></p>
                    </div>
                </div>
                        {% endif %}

            {% endfor %}

            <div class="pagination">
                <span class="step-links">
                    {% if post_list.has_previous %}
                        <a href="?page={{ post_list.previous_page_number }}">Предыдущий</a>
                    {% endif %}

                    <span class="current">
                        Страница {{ post_list.number }} из {{ post_list.paginator.num_pages }}.
                    </span>

                    {% if post_list.has_next %}
                        <a href="?page={{ post_list.next_page_number }}">Следующий</a>
                    {% endif %}
                </span>
            </div>
        </div>
    </div>
{% endblock %}

lab3/users/templates/users/editUser.html
{% extends 'boby.html' %}
{% block extrahead %}
    {% load static %}
    <link href="{% static 'css/forms.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-sm-6 col-sm-offset-3">
            <form id="form-login" method="POST" action=""  enctype="multipart/form-data">
                {% csrf_token %}
                {{ user_form }}
                <p><button class="btn btn-primary" type="submit">Сохранить</button></p>
            </form>
        </div>
    </div>
{% endblock %}

lab3/users/templates/users/index.html
{% extends 'boby.html' %}

{% block content %}
    <div class="row">
        <div class="col-sm-8 col-sm-offset-2">
            <h3 class="text-info text-center">Юзеры</h3>
            <hr>
            {% for user in user_list %}
                    <div class="row">
                        <div class="col-sm-12">
                            <a href="{% url 'users:blog' user.user.id %}">
                                <h4 class="text-info text-center">{{ user.user.username }}</h4>
                            </a>
                            <hr>
                        </div>
                    </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}