lab3/lab3/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('qq.urls')),
    url(r'^post/', include('post.urls', namespace="post")),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^accounts/', include('registration.backends.simple.urls')),
] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lab3/qq/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views
urlpatterns = [
    url(r'^Den/', views.Den, name='Den'),
    url(r'^sales/', views.sales, name='sales'),
    url(r'^news/', views.news, name='news'),
]

lab3/users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^edit/$', views.editUser, name='edit'),
    url(r'^blog/(?P<user_id>\d+)/$', views.userBlog, name='blog'),
]

lab3/templates/Boby.html
<meta charset="utf-8">
<html>

<head>
    {% load staticfiles %}
        <link href="{% static 'css/style.css' %}" rel='stylesheet' type='text/css'>
        <link href="{% static 'bootstrap-3.3.5/css/bootstrap.css' %}" rel="stylesheet">
        <link href="{% static 'css/footer.css' %}" rel="stylesheet">
        <link href="{% static 'css/images.css' %}" rel="stylesheet">
<title>Сервисная книжка</title>
</head>
<body bgcolor ="#ffffff" background="/static/ff.jpg">

        <div class="container-fluid">
                    <ul class ="nav nav-default" >
                    <ul class = "nav nav-tabs">
                        <li><a href='/news/'>Новости</a></li>
                        <li><a href='/sales/'>Продажа автомобилей</a></li>
                    {% if user.is_authenticated  %}
                       <li><a href="{% url 'auth_password_change' %}">Профиль</a></li>
                       <li><a href="{% url 'users:blog' user.id %}">Сервисная книжка</a></li>
                    {% endif %}
                        {% if user.is_authenticated %}
                           <li><a href="{% url 'auth_logout' %}">Выйти</a></li>
                        {% else %}
                           <li><a href="{% url 'auth_login' %}">Войти</a></li>
                        {% endif %}
                    </ul>
                    </ul>
        </div>
</body>
 {% block content %} {%endblock%}
</html>